### PR TITLE
Generate rbs as well

### PR DESCRIPTION
**Pull request by fundthmcalculus**
This adds support for generating the new ruby spec files (`.rbs`). Definitely a first draft, but want to get some feedback on this.

### CODE REVIEW

**Comment by fundthmcalculus** [comment]
@cb-heimdall review thoughts?

**Comment by fundthmcalculus** [comment]
@mdehoog any thoughts on this? It seems redundant to have a separate compiler for RBS.

**Comment by mdehoog** [comment]
I would prefer to keep them separate, for example as a `protoc-gen-rbs` plugin. Reasons being:
1. IMHO most folks would choose one or the other (`rbi`s or `rbs`s), rather than having them both generated
2. Discoverability: folks looking for a protobuf rbs generator would likely seach for `protoc-gen-rbs`
3. Maintainability: Coinbase doesn't yet use rbs files, so merging this change here would lead to unused / unmaintained features

**Comment by fundthmcalculus** [comment]
1. good call
2. I've tried Square's system, and it's unreliable and out of date. Hence this addition.
3. Fair point.

I'll release these changes as a separate package.

**Pull request closed without merging**
